imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@AdminBundle/Resources/config/services.yml" }
    - { resource: "@UserBundle/Resources/config/services.yml" }
#    - { resource: "@LoginBundle/Resources/config/services.yml" }
    - { resource: "@FosBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: vi

framework:
    #esi:             ~
    translator:      ~
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
#    port : 25
    spool:     { type: memory }
fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: FosBundle\Entity\User
    profile:
        form:
            type: FosBundle\Form\ProfileType
    registration:
        form:
            type: FosBundle\Form\RegistrationType
        confirmation:
            enabled:    true
            template:   FOSUserBundle:Registration:email.txt.twig
            from_email:
                address:     noreply@gmail.com
                sender_name:    DATN
    service:
            mailer: fos_user.mailer.default
#    resetting:
#            email:
#            template: email/password_resetting.email.twig


knp_paginator:
    page_range: 5                      # default page range used in pagination control
    default_options:
        page_name: page                # page query parameter name
        sort_field_name: sort          # sort field query parameter name
        sort_direction_name: direction # sort direction query parameter name
        distinct: true                 # ensure distinct results, useful when ORM queries are using GROUP BY statements
    template:
        pagination: KnpPaginatorBundle:Pagination:twitter_bootstrap_v3_pagination.html.twig  # sliding pagination controls template
        sortable: KnpPaginatorBundle:Pagination:sortable_link.html.twig # sort link template
#
easy_admin:
    entities:
#        - AppBundle\Entity\Product
#        - AppBundle\Entity\Category
#        - AppBundle\Entity\User
        Brand:
            label: 'Thương hiệu'
            class: UserBundle\Entity\Brands
        Salon:
            label: 'Salon Ô TÔ'
            class: UserBundle\Entity\ShopInfo
        BuyNews:
            label: 'Tin Mua'
            class: UserBundle\Entity\BuyNews
            disabled_actions: ['edit','new']
            edit:
                fields: [ 'code', 'title', 'price','date']
        SellNews:
            label: 'Tin Bán'
            class: UserBundle\Entity\SellNews
            disabled_actions: ['edit','new']
        User:
            label: 'Người dùng'
            class: FosBundle\Entity\User
            list:
                actions: ['show']
            edit:
                fields: [ 'phone', 'email', 'city','address', 'username_canonical','username']
#        - UserBundle\Entity\ShopInfo
#        - UserBundle\Entity\BuyNews
#        - FosBundle\Entity\User
    site_name: 'MobiHome'
