#fos:
#    resource: "@FosBundle/Resources/config/routing.yml"
#    prefix:   /
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/"
    type:     annotation
    prefix:   /ad824kn23t232u3g2g23dsiJgwefhwf83w
#login:
#    resource: "@LoginBundle/Resources/config/routing.yml"
#    prefix:   /
#user_routes:
#    resource: "@LoginBundle/Controller"
#    type: annotation
user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

admin:
    resource: "@AdminBundle/Resources/config/routing.yml"
    prefix:   /

#hello_test:
#    resource: "@HelloTestBundle/Resources/config/routing.xml"
#    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
#lucky_api:
#    path: api/lucky/{slug}
#    defaults:  { _controller: AppBundle:Lucky:apiNumber }
#lucky_number:
#    path: /lucky/number/{count}/{var2}
#    defaults:  { _controller: AppBundle:Lucky:number }
#lucky_tem:
#    path: /lucky/template/{count}
#    defaults:  { _controller: AppBundle:Lucky:template }
#lucky_redirect:
#    path: /lucky/redirect
#    defaults:  { _controller: AppBundle:Lucky:redi}
#login:
#    path:     /login
#    defaults: { _controller: AppBundle:Security:login }
#main_page:
#    path: /home
#    defaults: { _controller: AppBundle:Default:index }
#buy_news:
#    path: /buy
#    defaults: { _controller: AppBundle:Default:buyList }
#sell_news:
#    path: /sell
#    defaults: { _controller: AppBundle:Default:sellList }

