## To get started with security, check out the documentation:
## http://symfony.com/doc/current/book/security.html
#security:
#
#    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
#    providers:
#        in_memory:
#            memory: ~
#
#    firewalls:
#        # disables authentication for assets and the profiler, adapt it according to your needs
#        dev:
#            pattern: ^/(_(profiler|wdt)|css|images|js)/
#            security: false
#
#        main:
#            anonymous: ~
#            form_login:
#                login_path: login
#                check_path: login
#            # activate different ways to authenticate
#
#            # http_basic: ~
#            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate
#
#            # form_login: ~
#            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html

#Noi dung phia tren nguyen goc

security:
    encoders:
      Symfony\Component\Security\Core\User\User: plaintext
#      Custom\BookBundle\Entity\User: bcrypt
      FosBundle\Model\UserInterface: bcrypt
      FOS\UserBundle\Model\UserInterface: sha512
    role_hierarchy:
      ROLE_ADMIN:       ROLE_USER
      ROLE_SUPER_ADMIN: ROLE_ADMIN
    providers:
      fos_userbundle:
        id: fos_user.user_provider.username
#      chain_provider:
#        chain:
#          providers: [in_memory]
#      in_memory:
#        memory:
#          users:
#            admin: {password: adminpass, roles: ROLE_ADMIN}
    firewalls:
      main:
        pattern: ^/
        form_login:
          provider: fos_userbundle
          csrf_token_generator: security.csrf.token_manager
#          login_path: /login
#          check_path: /login_check
          default_target_path: /home
#        logout:
#          path: /logout
#          target: /home
#        security: true
        logout: true
        anonymous: true
    access_control:
            - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/admin/, role: ROLE_ADMIN }

#      - { path: /login, roles: [IS_AUTHENTICATED_ANONYMOUSLY,ROLE_USER] }
#      - { path: /user/edit, roles: ROLE_ADMIN }
#      - { path: /user/index, roles: ROLE_ADMIN }
#      - { path: /user/show, roles: ROLE_ADMIN }
#      - { path: /user/new, roles: IS_AUTHENTICATED_ANONYMOUSLY }
#      - { path: /.*, roles: [IS_AUTHENTICATED_ANONYMOUSLY,ROLE_USER] }
