<?php

namespace UserBundle\Repository;

/**
 * BrandsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BrandsRepository extends \Doctrine\ORM\EntityRepository
{
    public function getBrandName(){
            $queryBuilder = $this->getEntityManager()->createQueryBuilder()
                ->select('n')
                ->from($this->getEntityName(),'n');
            $result=$queryBuilder->getQuery()->getResult();
//        print_r($result);die;
            return $result;
    }
}
