<?php

namespace UserBundle\Repository;

use Symfony\Component\HttpFoundation\Request;

/**
 * SellNewsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SellNewsRepository extends \Doctrine\ORM\EntityRepository
{
    public function getDataSellNews(Request $request ){
        $brand=$request->query->get('brand');
        $status=$request->query->get('status');
        $price=$request->query->get('price');
        $year=$request->query->get('year');
        $city=$request->query->get('city');
        if(($brand!="")||($status!="")||($price!="")||($year!="")||($city!="")) {
            $queryBuilder = $this->getEntityManager()->createQueryBuilder()
                ->select('n')
                ->from($this->getEntityName(),'n');
            if($brand!=null){
                $queryBuilder->where('n.brandId= :brandId')
                    ->setParameter('brandId', $brand);
            }
            if($status!=null){
                $queryBuilder->andwhere('n.status LIKE :status')
                    ->setParameter('status', '%'.$status.'%');
            }
            if($year!=null){
                $queryBuilder->andwhere('n.year LIKE :year')
                    ->setParameter('year', '%'.$year.'%');
            }
            if($price!=null){
                if($price=="500000"){
                    $queryBuilder->andwhere('n.price > :price')
                        ->setParameter('price', 300000);
                }
                else{
                    $queryBuilder->andwhere('n.price < :price')
                        ->setParameter('price', $price);
                }
            }
            if($city!=null){
                $queryBuilder->andwhere('n.city LIKE :city')
                    ->setParameter('city', '%'.$city.'%');
            }

            $result=$queryBuilder->getQuery()->getResult();
            return $result;
        }
        else
        {
            return $this->getAllData();
        }
    }
    public function getAllData(){
        $queryBuilder = $this->getEntityManager()->createQueryBuilder()
            ->select('n')
            ->from($this->getEntityName(),'n')
            ->innerJoin('FosBundle\\Entity\\User','u','WITH', "u.id = n.userId")
            ->innerJoin('UserBundle\\Entity\\Brands','b','WITH', "b.id = n.brandId")
            ->innerJoin('UserBundle\\Entity\\ShopInfo','l','WITH', "n.shopId = l.shopLinkId");
        $result=$queryBuilder->getQuery()->getResult();
        return $result;
    }
    public function getNewsForUser($userId){
        $queryBuilder = $this->getEntityManager()->createQueryBuilder()
            ->select('n')
            ->from($this->getEntityName(),'n')
            ->where('n.userId = :userId')
            ->setParameter('userId',$userId);
//            ->innerJoin('FosBundle\\Entity\\User','u','WITH', "u.id = n.userId");
        $result=$queryBuilder->getQuery()->getResult();
//        echo "<pre>";
//        print_r($result);die;
        return $result;
    }
}
