<?php

namespace UserBundle\Repository;
use Symfony\Component\HttpFoundation\Request;
/**
 * ShopInfoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShopInfoRepository extends \Doctrine\ORM\EntityRepository
{
    public function setNewsOfShop($shopId){
        $queryBuilder = $this->getEntityManager()->createQueryBuilder()
            ->select('n')
            ->from('UserBundle\\Entity\\SellNews','n')
            ->where('n.shopId = :shopId')
            ->setParameter('shopId',$shopId);
        $result=$queryBuilder->getQuery()->getResult();
        return $result;
    }
    public function getDataSearch(Request $request){
        $searchString=$request->query->get('salonName');
        if($searchString!=""){
            $queryBuilder = $this->getEntityManager()->createQueryBuilder()
                ->select('n')
                ->from($this->getEntityName(),'n')
                ->where('n.name LIKE :salonName')
                ->setParameter('salonName', '%'.$searchString.'%');
            $result=$queryBuilder->getQuery()->getResult();
            return $result;
        }
        else
        {
            $queryBuilder = $this->getEntityManager()->createQueryBuilder()
                ->select('n')
                ->from($this->getEntityName(),'n');
            $result=$queryBuilder->getQuery()->getResult();
            return $result;
        }
    }
}
