<?php

namespace UserBundle\Repository;

/**
 * ShopLinkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShopLinkRepository extends \Doctrine\ORM\EntityRepository
{
}
