UserBundle\Entity\Brands:
    type: entity
    table: null
    repositoryClass: UserBundle\Repository\BrandsRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
    lifecycleCallbacks: {  }
